---
- name: Template .env
  ansible.builtin.template:
    src: "env.j2"
    mode: "{{ sftpgo_docker_docker_file_mode }}"
    dest: "{{ sftpgo_docker_base_dir }}/sftpgo/.env"

- name: Template sftpgo.env
  ansible.builtin.template:
    src: "sftpgo.env.j2"
    mode: "{{ sftpgo_docker_docker_file_mode }}"
    dest: "{{ sftpgo_docker_base_dir }}/sftpgo/sftpgo.env"

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    mode: "{{ sftpgo_docker_docker_file_mode }}"
    dest: "{{ sftpgo_docker_base_dir }}/sftpgo/docker-compose.yml"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_name: "{{ sftpgo_docker_docker_compose_project_prefix }}_sftpgo"
    project_src: "{{ sftpgo_docker_base_dir }}/sftpgo"
    state: present
